In [43]:
import numpy as np
# Fatoração LU
d = 4  # A dimensão da matriz (2x2,3x3,4x4)
# A matriz e matriz b
A = np.array([[ 1, 1, 0, 3],[ 2, 1, -1, 1],[ 3, -1, -1, 2],[ -1, 2, 3,-1]], dtype='double')
B = np.array([[ 2],[ 1],[ 5],[ -4]], dtype = 'double' )
print(f'\nA={A}\n')
print(f'\nB={B}\n')
# Se o determinante de todos os menores principais da matriz A forem não-nulos, então 
# a fatoração A=LU é unica
#-----------------------------4.A------------------------------#
print(f'DET1 = {np.linalg.det(A[:1,:1])}\n')
print(f'DET2 = {np.linalg.det(A[:2,:2])}\n')
print(f'DET3 = {np.linalg.det(A[:3,:3])}\n')
print(f'DET4 = {np.linalg.det(A[:4,:4])}\n')
#--------------------------------------------------------------#
# Matriz L e U
L = np.zeros((d,d))
U = np.zeros((d,d))
print(f'Matriz L inicialmente\n')
print(f'{L}\n')
print(f'Matriz U inicialmente\n')
print(f'{U}\n')
# Decomposição da matriz A em 
for i in range(d):
	# matriz U
	for k in range(i, d): 
		# somatório L(i, j) x U(j, k) 
		s = 0
		for j in range(i): 
			s += (L[i][j] * U[j][k]) 
		# verificando U(i, k) 
		U[i][k] = A[i][k] - s
	# Matriz L
	for k in range(i, d): 
		if (i == k):
			L[i][i] = 1 #Todos os valores na diagonal serão 1
		else:
			# somatório L(k, j) x U(j, i) 
			s = 0
			for j in range(i): 
				s += (L[k][j] * U[j][i])
			# verificando L(k, i)
			L[k][i] = int((A[k][i] - s) /	U[i][i])
#------------------------4.B-------------------------------#
print(f'Matriz L\n')
print(f'{L}\n')
print(f'Matriz U\n')
print(f'{U}\n')
#----------------------------------------------------------#
# Resolvendo a Matriz A
#  Ly=b
#  Ux=y
# ELIMINAÇÃO PROGRESSIVA
# Selecionando o número de linhas
n = L.shape[0]
# formato do arranjo dado, mas composto apenas de zeros.
Y = np.zeros_like( B, dtype=np.double)
# Substituição direta, inserindo a primeira linha já que a matriz é triangular superior
Y[0] = B[0] / L[0, 0]
# Um laço de repetição de cima para baixo
# Com inicio na segunda linha pois a primeira já foi resolvida.
for m in range(1, n):
	Y[m] = (B[m] - np.dot(L[m,:m], Y[:m])) / L[m,m]
# np.dot, em 2d multiplica as matrizes
print(f'Matriz Y\n')
print(f'{Y}\n')
# ELIMINAÇÃO REGRESSIVA
# Substitui n pelo números de linhas de U
p = U.shape[0] 
# formato do arranjo dado, mas composto apenas de zeros.
X = np.zeros_like( Y, dtype=np.double)
# Já que estamos fazendo uma retro-substituição
# Iniciando com a ultima linha.
X[-1] = Y[-1] / U[-1, -1]
# O laço de repetição será de baixo pra cima
# Inicia na penultima linha, a ultima já foi resolvida.
for m in range(p-2, -1, -1):
	X[m] = (Y[m] - np.dot(U[m,m:], X[m:])) / U[m,m]
#-------------------------4.D----------------------------#
print(f'Matriz X\n')
print(f'{X}\n')
#--------------------------------------------------------#


A=[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]


B=[[ 2.]
 [ 1.]
 [ 5.]
 [-4.]]

DET1 = 1.0

DET2 = -1.0

DET3 = -3.000000000000001

DET4 = 38.99999999999999

Matriz L inicialmente

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriz U inicialmente

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriz L

[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U

[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Matriz Y

[[  2.]
 [ -3.]
 [ 11.]
 [-11.]]

Matriz X

[[ 0.69230769]
 [-1.23076923]
 [ 0.        ]
 [ 0.84615385]]



### 4.C)

In [44]:
import numpy as np
for bi in range(4):
    # Fatoração LU
    d = 4  # A dimensão da matriz (2x2,3x3,4x4)
    # A matriz e matriz b
    A = np.array([[ 1, 1, 0, 3],[ 2, 1, -1, 1],[ 3, -1, -1, 2],[ -1, 2, 3, -1]])
    print(f'\nA={A}\n')
    if bi==0:
        B = np.array([[ 1],[ 0],[ 0],[ 0]], dtype = 'double' )
    elif bi==1:
        B = np.array([[ 0],[ 1],[ 0],[ 0]], dtype = 'double' )
    elif bi==2:
        B = np.array([[ 0],[ 0],[ 1],[ 0]], dtype = 'double' )
    elif bi==3:
        B = np.array([[ 0],[ 0],[ 0],[ 1]], dtype = 'double' )
    print(f'\nB={B}\n')
    # Se o determinante de todos os menores principais da matriz A forem não-nulos, então
    # a fatoração A=LU é unica
    #-----------------------------4.A------------------------------#
    print(f'DET1 = {np.linalg.det(A[:1,:1])}\n')
    print(f'DET2 = {np.linalg.det(A[:2,:2])}\n')
    print(f'DET3 = {np.linalg.det(A[:3,:3])}\n')
    print(f'DET4 = {np.linalg.det(A[:4,:4])}\n')
    #--------------------------------------------------------------#
    # Matriz L e U
    L = np.zeros((d,d))
    U = np.zeros((d,d))
    print(f'Matriz L inicialmente\n')
    print(f'{L}\n')
    print(f'Matriz U inicialmente\n')
    print(f'{U}\n')
    # Decomposição da matriz A em 
    for i in range(d):
        # matriz U
        for k in range(i, d):
            # somatório L(i, j) x U(j, k)
            s = 0
            for j in range(i):
                s += (L[i][j] * U[j][k])
            # verificando U(i, k)
            U[i][k] = A[i][k] - s
        # Matriz L
        for k in range(i, d):
            if (i == k):
                L[i][i] = 1 #Todos os valores na diagonal serão 1
            else:
                # somatório L(k, j) x U(j, i)
                s = 0
                for j in range(i):
                    s += (L[k][j] * U[j][i])
                # verificando L(k, i)
                L[k][i] = int((A[k][i] - s) /	U[i][i])
    #------------------------4.B-------------------------------#
    print(f'Matriz L\n')
    print(f'{L}\n')
    print(f'Matriz U\n')
    print(f'{U}\n')
    #----------------------------------------------------------#
    # Resolvendo a Matriz A
    #  Ly=b
    #  Ux=y
    # ELIMINAÇÃO PROGRESSIVA
    # Selecionando o número de linhas
    n = L.shape[0]
    # formato do arranjo dado, mas composto apenas de zeros.
    Y = np.zeros_like( B, dtype=np.double)
    # Substituição direta, inserindo a primeira linha já que a matriz é triangular superior
    Y[0] = B[0] / L[0, 0]
    # Um laço de repetição de cima para baixo
    # Com inicio na segunda linha pois a primeira já foi resolvida.
    for m in range(1, n):
        Y[m] = (B[m] - np.dot(L[m,:m], Y[:m])) / L[m,m]
    # np.dot, em 2d multiplica as matrizes
    print(f'Matriz Y\n')
    print(f'{Y}\n')
    # ELIMINAÇÃO REGRESSIVA
    # Substitui n pelo números de linhas de U
    p = U.shape[0]
    # formato do arranjo dado, mas composto apenas de zeros.
    X = np.zeros_like( Y, dtype=np.double)
    # Já que estamos fazendo uma retro-substituição
    # Iniciando com a ultima linha.
    X[-1] = Y[-1] / U[-1, -1]
    # O laço de repetição será de baixo pra cima
    # Inicia na penultima linha, a ultima já foi resolvida.
    for m in range(p-2, -1, -1):
        X[m] = (Y[m] - np.dot(U[m,m:], X[m:])) / U[m,m]
    #-------------------------4.D----------------------------#
    print(f'Matriz X\n')
    print(f'Coluna {bi+1} da matriz inversa é \n X{bi+1} = {X}\n')
    #--------------------------------------------------------#


A=[[ 1  1  0  3]
 [ 2  1 -1  1]
 [ 3 -1 -1  2]
 [-1  2  3 -1]]


B=[[1.]
 [0.]
 [0.]
 [0.]]

DET1 = 1.0

DET2 = -1.0

DET3 = -3.000000000000001

DET4 = 38.99999999999999

Matriz L inicialmente

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriz U inicialmente

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriz L

[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U

[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Matriz Y

[[ 1.]
 [-2.]
 [ 5.]
 [-5.]]

Matriz X

Coluna 1 da matriz inversa é 
 X1 = [[-0.23076923]
 [ 0.07692308]
 [ 0.        ]
 [ 0.38461538]]


A=[[ 1  1  0  3]
 [ 2  1 -1  1]
 [ 3 -1 -1  2]
 [-1  2  3 -1]]


B=[[0.]
 [1.]
 [0.]
 [0.]]

DET1 = 1.0

DET2 = -1.0

DET3 = -3.000000000000001

DET4 = 38.99999999999999

Matriz L inicialmente

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriz U inicialmente

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 