In [5]:
#### DECOMPOSIÇÃO DE CHOLESKY
import math as m
import numpy as np
d = 3 #Número de dimensões da matriz 
A = np.array([[ 4, -1, 1],[ -1, 4.25, 1.65],[ 1, 1.65, 3.75]])  #Matriz a ser decomposta
B = np.array([[ 0],[ 7],[ 4]])
G = np.zeros((d,d))
T = np.zeros((d,d))
print(f'Matriz A:\n\n{A}\n\n Matriz B\n\n{B}\n\n Matriz G\n\n{G}\n\n')
vv = True
for i1 in range(d):
    for j1 in range(i1 + 1):
        if A[i1][j1]!=A[j1][i1]:
            print(f'\nA matriz não é simétrica!')
            vv = False
            break
if vv==True:
    print(f'\nA matriz é simétrica\n')
#--------------------------menores principais-----------------------------#
print(f'\nMenores principais\n')
print(f'DET1 = {np.linalg.det(A[:1,:1])}\n')
print(f'DET2 = {np.linalg.det(A[:2,:2])}\n')
print(f'DET3 = {np.linalg.det(A[:3,:3])}\n')
#--------------------------------------------------------#
# Decompondo a matriz A em G
for i in range(d):
    for j in range(i + 1):
        s = 0
#Somatório para a diagonal	
        if j==i:
            for k in range(j):
                s += m.pow(G[j][k], 2)
#se gii então aii=gii^2(para i=1 o g11 será apenas raiz de aii)
            G[j][j] = m.sqrt( A[j][j] - s )
#Que é a mesma coisa de gii=raiz(aii)
        else:
# testando para  L(i, j) 
# usando L(j, j)
            for k in range(j):
                s += (G[i][k] * G[j][k])
# para gij sendo i!=j
            if G[j][j] > 0:
                G[i][j] = int((A[i][j] - s)/G[j][j])
#quando gi1 então será ai1/g11
for i in range(d):
    for j in range(d):
        T[i][j] = G[j][i]
#Transpondo a matriz G
print("Matriz G\n\n")
print(G)
print('\nMatriz G^T\n\n')
print(T)
#Resolvendo a Matriz A
#  g.y=b
#  g^t.x=y
# ELIMINAÇÃO PROGRESSIVA
#Selecionando o número de linhas
n = G.shape[0]
#formato do arranjo dado, mas composto apenas de zeros.
Y = np.zeros_like(B, dtype=np.double)
#Substituição direta, inserindo a primeira linha já que a matriz é triangular superior
Y[0] = B[0] / G[0, 0]
#Um laço de repetição de cima para baixo
#Com inicio na segunda linha pois a primeira já foi resolvida.
for m in range(1, n):
	Y[m] = (B[m] - np.dot(G[m,:m], Y[:m])) / G[m,m]
#np.dot, em 2d multiplica as matrizes
print(f'Matriz Y\n')
print(f'{Y}\n')
# ELIMINAÇÃO REGRESSIVA
#Substitui n pelo números de linhas de U
n = T.shape[0]
#formato do arranjo dado, mas composto apenas de zeros.
X = np.zeros_like(Y, dtype=np.double)
#Já que estamos fazendo uma retro-substituição
#Iniciando com a ultima linha.
X[-1] = Y[-1] / T[-1, -1]
#O laço de repetição será de baixo pra cima
#Inicia na penultima linha, a ultima já foi resolvida.
for m in range(n-2, -1, -1):
	X[m] = (Y[m] - np.dot(T[m,m:], X[m:])) / T[m,m]
#-------------------------4.D----------------------------#
print(f'Matriz X\n')
print(f'{X}\n')
#--------------------------------------------------------#

Matriz A:

[[ 4.   -1.    1.  ]
 [-1.    4.25  1.65]
 [ 1.    1.65  3.75]]

 Matriz B

[[0]
 [7]
 [4]]

 Matriz G

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



A matriz é simétrica


Menores principais

DET1 = 4.0

DET2 = 15.999999999999998

DET3 = 41.55999999999999

Matriz G


[[2.         0.         0.        ]
 [0.         2.06155281 0.        ]
 [0.         0.         1.93649167]]

Matriz G^T


[[2.         0.         0.        ]
 [0.         2.06155281 0.        ]
 [0.         0.         1.93649167]]
Matriz Y

[[0.        ]
 [3.39549875]
 [2.06559112]]

Matriz X

[[0.        ]
 [1.64705882]
 [1.06666667]]

